language: python

python:
  - 2.7
  - 3.5

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5

env:
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.11
  - DJANGO_VERSION=1.8.18
  - DJANGO_VERSION=1.9.13
  - DJANGO_VERSION=1.10.6
  - DJANGO_VERSION=1.11.3
  - DJANGO_VERSION=2.0.13
  - DJANGO_VERSION=2.1.7

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install beautifulsoup4
  - pip install coveralls
  - pip install tox
  - python setup.py -q install

script:
  - tox

after_success:
  - coveralls
