language: python

python:
  - "2.7"

env:
  - DJANGO_VERSION=1.7.11
  - DJANGO_VERSION=1.8.7

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install beautifulsoup4
  - python setup.py -q install

script:
  - py.test .
