language: python

python:
  - "2.7"
  - "3.5"

env:
  - DJANGO_VERSION=1.7.11
  - DJANGO_VERSION=1.8.7
  - DJANGO_VERSION=1.9.0

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install beautifulsoup4
  - pip install tox
  - python setup.py -q install

script:
  - tox
